<html>
<head>
<script type="application/ld+json">
<#noautoesc>
${jsonLd}
</#noautoesc>
</script>
</head>
<body>
	<p>Dear Madam/Sir ${underName.name},<br/>
     You have successfully reserved ${description} at ${reservationFor.name}. Your reservation number is ${reservationId}.<br/>
     If you have swished, show this email at the entrance so we can check the payment from your phone number: ${underName.telephone}</p>
</body>
</html>