<html>
<body>
<h4>Dear ${name},</h4>
<p>Malmö Improvisatorium is looking forward to seeing you at our Contagious show this Saturday!<br/> 
Please remember to bring along your shiny smile and be ready for an evening of fun!<br/> 
<#if paid>
Thanks for your payment through swish. Your seat will be extra warm because of this!<br/>
<#else>
As you plan to pay for the tickets at the entrance, please be welcome to come a few minutes early.<br/> 
If you know that you are not planning to come, please let us know (reply to this email) - improv shows are in great demand these days :)<br/> 
</#if>
<br/> 
See you there! (Geographically: MAF Scene 2, Norra Skolgatan 12, Malmö, 14th October, 18:30)<br/> 
<br/> 
Your Improvisers
</p>
</body>
</html>